- name: Verify apache2 is installed & installs it if not
  ansible.builtin.apt:
    name: apache2
    state: present

- name: Verify apache2 is running & start it if not
  ansible.builtin.systemd_service:
    name: apache2
    state: started
    enabled: yes

- name: Verify apache2 is listening on port 80 & probe for it
  ansible.builtin.wait_for:
    host: localhost
    port: "{{ default_listen_port }}"

- name: Copy the HTML file to the apache2 document root
  ansible.builtin.copy:
    src: beautiful_frontend.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
    force: true