name: Terraform Unit Tests

on:
  push:

permissions:
  security-events: write # Needed to upload-sarif
  contents: read # Needed to clone repo
  actions: read # Potentially needed for private repositories (see https://github.com/github/codeql-action/issues/2117)

jobs:
  terraform-unit-tests:
    name: Terraform Unit Tests
    runs-on: ubuntu-24.04
    
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init -backend=false

    # Validate terraform files
    - name: Terraform Validate
      run: terraform validate
    
    # Perform a security scan of the terraform code using checkov
    - name: Run Checkov action
      id: checkov
      uses: bridgecrewio/checkov-action@master
      with: 
        framework: terraform
        # Soft fail on:
          # INFO Severity 
          # LOW Severity
          # CKV_AZURE_33: resource test is deprecated, replaced with azurerm_storage_account_queue_properties resource
          # CKV_AZURE_40: Ignore explicit experation date, key rotation and experation are managed automatically in the current config
        soft_fail_on: INFO,LOW,CKV_AZURE_33,CKV_AZURE_40